Update build-kata-ami.yaml

diff --git a/.github/workflows/build-kata-ami.yaml b/.github/workflows/build-kata-ami.yaml
--- a/.github/workflows/build-kata-ami.yaml
+++ b/.github/workflows/build-kata-ami.yaml
@@ -1,51 +1,189 @@
 name: Build Kata AMI
 
 on:
+  push: 
+    branches: 
+      - garvit/ci-pipeline
   workflow_dispatch:
 
-jobs:
-  setup-environment:
-    name: Set Up Environment
-    runs-on: ubuntu-latest
+permissions:
+  contents: read
+  packages: write
+  id-token: write
 
+jobs:
+  build-kernel:
+    runs-on: ubuntu-x86-kernel-builder
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+        with:
+          show-progress: false
+
+      - name: Clone Linux repository
+        uses: actions/checkout@v4
+        with:
+          token: ${{ secrets.GH_TOKEN }}
+          repository: virt-pvm/linux
+          ref: e7fb41a749cb4ff541f0876629921f1f9b39a805
+          path: ./kata/linux-images/linux
+          fetch-depth: 1
+          show-progress: false
+
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
+      
+      - name: Login to registry
+        uses: docker/login-action@v3
+        with:
+          registry: ghcr.io
+          username: devzero-inc
+          password: ${{ secrets.GH_TOKEN }}
+
+      - name: Build kernel docker image
+        uses: docker/build-push-action@v6
+        with:
+          context: ./kata/linux-images
+          file: ./kata/linux-images/Dockerfile.host
+          tags: ghcr.io/devzero-inc/host-pvm-linux:latest
+          push: true
+      
+      - name: Build guest docker image
+        uses: docker/build-push-action@v6
+        with:
+          context: ./kata/linux-images
+          file: ./kata/linux-images/Dockerfile.guest
+          tags: ghcr.io/devzero-inc/guest-pvm-linux:latest
+          push: true
+
+  build-ami:
+    name: Build AMI with Packer
+    runs-on: ubuntu-latest
+    needs: build-kernel
     steps:
       - name: Checkout Repository
-        uses: actions/checkout@v3
+        uses: actions/checkout@v4
+        with:
+          token: ${{ secrets.GH_TOKEN }}
+
+      - name: Pull and Create Temporary Container
+        run: |
+          docker pull ghcr.io/devzero-inc/host-pvm-linux:latest
+          docker pull ghcr.io/devzero-inc/guest-pvm-linux:latest
+
+          CONTAINER_ID=$(docker create ghcr.io/devzero-inc/host-pvm-linux:latest)
+          docker cp "$CONTAINER_ID:/kernel-6.7.0_dz_pvm_host-1.x86_64.rpm" ./kata/packer/kernel.rpm
+          docker cp "$CONTAINER_ID:/kernel-headers-6.7.0_dz_pvm_host-1.x86_64.rpm" ./kata/packer/kernel-headers.rpm
+          docker cp "$CONTAINER_ID:/kernel-devel-6.7.0_dz_pvm_host-1.x86_64.rpm" ./kata/packer/kernel-devel.rpm
+          docker rm "$CONTAINER_ID"
+
+          CONTAINER_ID_GUEST=$(docker create ghcr.io/devzero-inc/guest-pvm-linux:latest)
+          docker cp "$CONTAINER_ID_GUEST:/guest-vmlinux" ./kata/packer/guest-vmlinux
+          docker rm "$CONTAINER_ID_GUEST"
 
       - name: Configure AWS Credentials
         uses: aws-actions/configure-aws-credentials@v4
         with:
-          role-to-assume: arn:aws:iam::<AWS_ACCOUNT_ID>:role/<ROLE_NAME> # Replace with your AWS role ARN
+          role-to-assume: arn:aws:iam::484907513542:role/github-actions-oidc-role
           aws-region: us-west-1
 
-      - name: Install Dependencies
+      - name: Initialize and Build AMI
         run: |
-          sudo apt-get update
-          sudo apt-get install -y git unzip docker.io
+          cd ./kata/packer
+          packer init .
+          packer build .
 
-      - name: Install AWS CLI
-        run: |
-          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
-          unzip awscliv2.zip
-          sudo ./aws/install
+  # build-host-container:
+  #   name: Build Host Container
+  #   runs-on: ubuntu-latest
+  #   needs: setup-environment
+  #   steps:
+  #     - name: Checkout Repository
+  #       uses: actions/checkout@v4
+  #       with:
+  #         token: ${{ secrets.GH_TOKEN }}
 
-      - name: Install Packer
-        run: |
-          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
-          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
-          sudo apt-get update && sudo apt-get install -y packer
+  #     - name: Navigate to Linux Images Directory and Clone Repository
+  #       run: |
+  #         cd ./kata/linux-images || { echo "Error: Directory kata/linux-images not found."; exit 1; }
+  #         git clone https://github.com/virt-pvm/linux.git --depth=1
 
-  run-build-script:
-    name: Run Build Script
-    runs-on: ubuntu-latest
-    needs: setup-environment
+  #     - name: Set up Docker Buildx
+  #       uses: docker/setup-buildx-action@v2
 
-    steps:
-      - name: Checkout Repository
-        uses: actions/checkout@v3
+  #     - name: Build Docker Image for Host
+  #       uses: docker/build-push-action@v5
+  #       with:
+  #         context: .
+  #         file: ./kata/linux-images/Dockerfile.host
+  #         tags: linux-image-host:latest
+  #         cache-from: type=gha
+  #         cache-to: type=gha,mode=max
+  #         load: true
 
-      - name: Run Build Script
-        env:
-          GH_TOKEN: ${{ secrets.GH_TOKEN }} 
-        run: ./kata/packer/build-ami.sh
+  # build-guest-container:
+  #   name: Build Guest Container
+  #   runs-on: ubuntu-latest
+  #   needs: setup-environment
+  #   steps:
+  #     - name: Checkout Repository
+  #       uses: actions/checkout@v4
+  #       with:
+  #         token: ${{ secrets.GH_TOKEN }}
+
+  #     - name: Navigate to Linux Images Directory and Clone Repository
+  #       run: |
+  #         cd ./kata/linux-images || { echo "Error: Directory kata/linux-images not found."; exit 1; }
+  #         git clone https://github.com/virt-pvm/linux.git --depth=1
+
+  #     - name: Set up Docker Buildx
+  #       uses: docker/setup-buildx-action@v2
+
+  #     - name: Build Docker Image for Guest
+  #       uses: docker/build-push-action@v5
+  #       with:
+  #         context: .
+  #         file: ./kata/linux-images/Dockerfile.guest
+  #         tags: linux-image-guest:latest
+  #         cache-from: type=gha
+  #         cache-to: type=gha,mode=max
+  #         load: true
+
+  # extract-files:
+  #   name: Extract Kernel Files from Containers
+  #   runs-on: ubuntu-latest
+  #   needs: [build-host-container, build-guest-container]
+  #   steps:
+  #     - name: Checkout Repository
+  #       uses: actions/checkout@v4
+  #       with:
+  #         token: ${{ secrets.GH_TOKEN }}
+
+  #     - name: Create Temporary Container and Copy Files
+  #       run: |
+  #         CONTAINER_ID=$(docker create linux-image-host:latest)
+  #         docker cp "$CONTAINER_ID:/kernel-6.7.0_dz_pvm_host-1.x86_64.rpm" self-hosted/kata/packer/kernel.rpm
+  #         docker cp "$CONTAINER_ID:/kernel-headers-6.7.0_dz_pvm_host-1.x86_64.rpm" self-hosted/kata/packer/kernel-headers.rpm
+  #         docker cp "$CONTAINER_ID:/kernel-devel-6.7.0_dz_pvm_host-1.x86_64.rpm" self-hosted/kata/packer/kernel-devel.rpm
+  #         docker rm "$CONTAINER_ID"
+
+  #         CONTAINER_ID_GUEST=$(docker create linux-image-guest:latest)
+  #         docker cp "$CONTAINER_ID_GUEST:/guest-vmlinux" self-hosted/kata/packer/guest-vmlinux
+  #         docker rm "$CONTAINER_ID_GUEST"
+
+  # build-ami:
+  #   name: Build AMI with Packer
+  #   runs-on: ubuntu-latest
+  #   needs: extract-files
+  #   steps:
+  #     - name: Checkout Repository
+  #       uses: actions/checkout@v4
+  #       with:
+  #         token: ${{ secrets.GH_TOKEN }}
+
+  #     - name: Initialize and Build AMI
+  #       run: |
+  #         cd ./kata/packer
+  #         packer init .
+  #         packer build .
 
