ci to push helm charts

diff --git a/.github/workflows/push-helm-charts.yaml b/.github/workflows/push-helm-charts.yaml
--- a/.github/workflows/push-helm-charts.yaml
+++ b/.github/workflows/push-helm-charts.yaml
@@ -81,6 +81,8 @@ jobs:
           echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
           sed -i "s/^version:.*/version: $NEW_VERSION/" charts/${{ matrix.chart }}/Chart.yaml
 
+          cat charts/${{ matrix.chart }}/Chart.yaml
+
       - name: Package Helm Chart
         run: |
           helm package charts/${{ matrix.chart }}
@@ -115,6 +117,9 @@ jobs:
           for chart in dz-control-plane dz-control-plane-deps dz-data-plane dz-data-plane-deps; do
             if [ -f "downloaded_charts/chart-$chart/Chart.yaml" ]; then
               mv "downloaded_charts/chart-$chart/Chart.yaml" "charts/$chart/Chart.yaml"
+            else
+              echo "Error: Chart.yaml for $chart not found in artifact!"
+              exit 1
             fi
           done
 
@@ -130,6 +135,7 @@ jobs:
           git config --global user.email "github-actions@github.com"
 
           git add charts/*/Chart.yaml
+          git status
           git commit -m "chore: bump Helm chart versions" || echo "No changes to commit"
           git push origin "$BRANCH_NAME"
 
